module Update.SessionMsg exposing (SessionMsg(..))

import Data.AccessToken exposing (AccessToken)
import Data.Blueprint exposing (Blueprint)
import Data.BlueprintId exposing (BlueprintId)
import Data.CampaignId exposing (CampaignId)
import Data.Draft exposing (Draft)
import Data.DraftId exposing (DraftId)
import Data.GetError exposing (GetError)
import Data.HighScore exposing (HighScore)
import Data.Level exposing (Level)
import Data.LevelId exposing (LevelId)
import Data.SaveError exposing (SaveError)
import Data.Solution exposing (Solution)
import Data.SolutionId exposing (SolutionId)
import Data.SubmitSolutionError exposing (SubmitSolutionError)
import Data.UserInfo exposing (UserInfo)


type SessionMsg
    = GeneratedSolution Solution
    | GotDeleteDraftByDraftIdResponse DraftId (Maybe SaveError)
    | GotLoadDraftByDraftIdResponse DraftId (Result GetError (Maybe Draft))
    | GotLoadDraftsByLevelIdResponse LevelId (Result GetError (List Draft))
    | GotLoadHighScoreResponse LevelId (Result GetError HighScore)
    | GotLoadLevelByLevelIdResponse LevelId (Result GetError (Maybe Level))
    | GotLoadLevelsByCampaignIdResponse CampaignId (Result GetError (List Level))
    | GotLoadBlueprintResponse BlueprintId (Result GetError (Maybe Blueprint))
    | GotLoadBlueprintsResponse (Result GetError (List Blueprint))
    | GotLoadSolutionBySolutionIdResponse SolutionId (Result GetError (Maybe Solution))
    | GotLoadSolutionsByLevelIdResponse LevelId (Result GetError (List Solution))
    | GotLoadSolutionsByLevelIdsResponse (List LevelId) (Result GetError (List Solution))
    | GotLoadSolutionsBySolutionIdResponse SolutionId (Result GetError (Maybe Solution))
    | GotLoadUserInfoResponse AccessToken (Result GetError UserInfo)
    | GotSaveDraftResponse Draft (Maybe SaveError)
    | GotDeleteBlueprintResponse BlueprintId (Maybe SaveError)
    | GotSaveBlueprintResponse Blueprint (Maybe SaveError)
    | GotSaveSolutionResponse Solution (Maybe SubmitSolutionError)
    | GotDeleteSolutionBySolutionIdResponse SolutionId (Maybe SaveError)
